# Generated by Django 2.1 on 2018-08-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanxiangce', '0002_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
